name: ESLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Restore node_modules Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: eslint-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          eslint-${{ env.cache-name }}-
          eslint-

    - name: Install Dependencies
      run: npm i

    - name: Run ESLint
      run: npx eslint .
